<?php

declare(strict_types=1);

namespace JonPurvis\Uninspire\Console\Commands;

use Illuminate\Console\Command;

class UninspireCommand extends Command
{
    /**
     * The signature of the command.
     *
     * @var string
     */
    protected $signature = 'uninspire';

    /**
     * The description of the command.
     *
     * @var string
     */
    protected $description = 'Display an uninspiring quote';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
       $this->comment(collect([
            "Expect the mediocre, and you won't be disappointed.",
            "Why aim for the stars when you can settle for the ceiling?",
            "Dream small, achieve even smaller",
            "Success is overrated; have you tried failure?",
            "Why run when you can walk slowly?",
            "Procrastination: Because there's always tomorrow",
            "Set your goals low, and you'll never be let down",
            "The road to nowhere is paved with indifference",
            "Mistakes: I make them daily",
            "Ambition is for overachievers",
            "Mediocrity is my comfort zone",
            "Average is the new exceptional",
            "Why be a trailblazer when you can follow the herd?",
            "Standing out is too much effort; blending in is just fine",
            "I'm not lazy; I'm conserving energy",
            "The glass is half empty because I drank the other half",
            "Adventure? No thanks, I'll pass",
            "Optimism: It's just a waste of time",
            "Why fly when you can crawl?",
            "Stagnation is my happy place",
            "Life is a series of disappointments, so get used to it",
            "Success is for those who care too much",
            "Why be a go-getter when you can be a go-slower?",
            "Taking risks is so 20th century",
            "Dreams are for people who can't accept reality",
            "Overachievers never truly relax",
            "Effort is overrated; I prefer convenience",
            "Why aim high when you can aim low and still miss?",
            "Good things come to those who wait forever",
            "Expectations are the root of all disappointment",
            "Why be motivated when you can be mediocre?",
            "Settling for less is my life motto",
            "Failing is the first step towards giving up",
            "Why be extraordinary when you can be ordinary?",
            "Procrastination is my superpower",
            "Life is a series of boring moments",
            "Why stand out when you can blend in seamlessly?",
            "Perfectionism is for perfectionists",
            "Taking shortcuts is the way to go",
            "Why hustle when you can snooze?",
            "I'd rather underachieve than overexert",
            "Why try when you can just hope for the best?",
            "Why be ambitious when you can be apathetic?",
            "Success is for those who can't accept failure",
            "Life is a never-ending cycle of monotony",
            "Why climb mountains when you can stay in bed?",
            "Ambition leads to exhaustion",
            "Why reach for the stars when you can gaze at them from afar?",
            "Dreams are for people with too much time on their hands",
            "Why be a winner when you can be a whiner?",
            "Why be a leader when you can be a follower?",
            "Mediocrity is the key to an uneventful life",
            "Why be punctual when you can be perpetually late?",
            "Effort is for those who can't avoid it",
            "Why excel when you can excel at mediocrity?",
            "Setting goals is just a form of self-punishment",
            "I'm not a quitter; I'm a non-starter",
            "Why be a legend when you can be forgettable?",
            "Life is a never-ending sea of monotony",
            "Adventure is overrated; routine is where it's at",
            "Ambition is for the overly optimistic",
            "Why achieve greatness when you can achieve averageness?",
            "Why have high hopes when you can have low expectations?",
            "Why innovate when you can imitate?",
            "Why be enthusiastic when you can be indifferent?",
            "Why be proactive when you can be passive?",
            "Why aim for the moon when you can stay grounded?",
            "Striving for excellence? Nah, I'm good with mediocrity",
            "I'm not a slacker; I'm a strategic energy saver",
            "Ambition is just another word for unnecessary stress",
            "Optimism is for the delusional",
            "Why be a trendsetter when you can be a trend-follower?",
            "Why make waves when you can float along peacefully?",
            "I'm not avoiding work; I'm perfecting my leisure skills",
            "Why be fearless when you can fear everything?",
            "Life's too short to bother with success",
            "Why try when you can fail effortlessly?",
            "Why be a pioneer when you can be a settler?",
            "Overachievement is for overrated people",
            "Life is a series of uninspiring moments",
            "Why strive for greatness when you can settle for adequacy?",
            "Optimism is the path to disappointment",
            "Why be ambitious when you can be complacent?",
            "Why be a hero when you can be a zero?",
            "Taking risks is for those who care too much",
            "Why be a doer when you can be a dreamer?",
            "I'm not lazy; I'm conserving my motivation",
            "Why be diligent when you can be disinterested?",
            "Why aim for the best when you can aim for the rest?",
            "Life is a long journey to mediocrity",
            "Success is for the overly enthusiastic",
            "Why reach for the stars when you can aim for the gutter?",
            "Why work hard when you can hardly work?",
            "Effort is for those with too much time on their hands",
            "Why excel when you can embrace mediocrity?",
            "Why set goals when you can simply drift?",
            "I'm not a quitter; I'm a professional procrastinator",
            "Why be a winner when you can be a non-competitor?",
            "Ambition is the road to nowhere",
            "Why be creative when you can copy and paste?",
            "Success is for people with too much ambition",
            "Why take action when you can take a nap?",
            "Life is a collection of missed opportunities",
            "Why achieve when you can underachieve?",
            "Why be a legend in your own mind when you can be utterly forgettable?",
            "Why be a winner when you can be a watcher?",
            "Why aspire when you can retire?",
            "Optimism is a trap; pessimism is reality",
            "Why aim for the sky when you can aim for the basement?",
            "Life is a never-ending series of letdowns",
            "Ambition is for those who can't sit still",
            "Why be driven when you can be a passenger?",
            "Why try to fit in when you can stand out for being mediocre?",
            "Success is for those with too much energy",
            "Life is a never-ending parade of blah",
            "Why be enthusiastic when you can be blah?",
            "Why have high standards when you can have none at all?",
            "Why make a splash when you can make a ripple?",
            "I'm not avoiding challenges; I'm embracing ease",
            "Why be a rock star when you can be a one-hit wonder?",
            "Why set the world on fire when you can watch it burn?",
            "Why be a big fish in a big pond when you can be a small fish in a small p,uddle?",
            "Why be the best when you can be the rest?",
            "Life is a series of bland moments",
            "Ambition is for people with too much hope",
            "Success is for those who can't handle boredom",
            "Why be a mover and shaker when you can be a sitter and sleeper?",
            "Life is a never-ending series of mehs",
            "Ambition is the enemy of relaxation",
            "Why rise and shine when you can snooze and lose?",
            "Why be a visionary when you can lack imagination?",
            "Life is a journey to nowhere in particular",
            "Why strive when you can simply survive?",
            "Optimism is for dreamers; I'm a realist",
            "Why lead when you can follow blindly?",
            "Ambition is for those with something to prove",
            "Why be remarkable when you can be unnoticeable?",
            "Life is a cycle of mediocrity",
            "Ambition is for the restless",
            "Why push boundaries when you can stay within your comfort zone?",
            "Why stand tall when you can slouch comfortably?",
            "Optimism is a delusion; reality is mundane",
            "Why be an overachiever when you can be an underwhelming achiever?",
            "Ambition is a path to burnout",
            "Life is a series of forgettable moments",
            "Why be a force of nature when you can be a gentle breeze?",
            "Why make history when you can be a footnote?",
            "Life is a never-ending cycle of sameness",
            "Why be unique when you can be generic?",
            "Why be an inspiration when you can be an afterthought?",
            "Why go big when you can go home?",
            "Ambition is a path to unnecessary stress",
            "Why challenge yourself when you can stay unchallenged?",
            "Why be first when you can be last and least?",
            "Life is a never-ending treadmill of mediocrity",
            "Ambition is for the young and restless",
            "Why seek fame when you can seek obscurity?",
            "Why push the envelope when you can seal it shut?",
            "Why be a front-runner when you can be a backbencher?",
            "Life is a monotonous melody",
            "Ambition is for those who can't accept contentment",
            "Why be a hero when you can be a sidekick?",
            "Why make a mark when you can leave no trace?",
            "Life is a never-ending loop of blah",
            "Why chase dreams when you can chase your tail?",
            "Ambition is a fool's game",
            "Why set the pace when you can lag behind?",
            "Why be an innovator when you can be a replicator?",
            "Ambition is for the misguided",
            "Why break barriers when you can sit behind them?",
            "Why shine bright when you can dimly glow?",
            "Life is a continuous cycle of blah",
            "Why seek greatness when you can seek anonymity?",
            "Ambition is a path to exhaustion",
            "Why strive for the top when you can comfortably settle at the bottom?",
            "Life is a series of uninspiring events",
            "Why be a beacon of hope when you can be a beacon of blah?",
            "Ambition is for the overly zealous",
            "Why take the lead when you can take a back seat?",
            "Life is a continuous loop of meh",
            "Why make a difference when you can make a mess?",
            "Ambition is a wild goose chase",
            "Why stand out when you can stand back?",
            "Life is a tedious trail of meh",
            "Why be a game-changer when you can be a spectator?",
            "Ambition is a mirage",
            "Why blaze a trail when you can leave no trace?",
            "Why be a spark when you can be a flicker?",
            "Life is a relentless rotation of meh",
            "Why be a luminary when you can be a shadow?",
            "Ambition is a myth",
            "Why forge ahead when you can lag behind?",
            "Life is a never-ending rotation of blah",
            "Why make an impact when you can make an indentation?",
            "Ambition is for the weary",
            "Why be a trailblazer when you can be a trail follower?",
            "Life is a relentless cycle of blah",
            "Why rise above when you can blend in below?",
            "Why be a beacon of light when you can be a beacon of blah?",
            "Life is a monotonous march of meh",
           "Why break the mold when you can be molded?",
           "Why create when you can consume?",
           "Achievement is just another form of stress",
           "Why aim for perfection when you can settle for adequacy?",
           "Success is just a higher level of problem",
           "Why be original when you can be a replica?",
           "Why strive for more when you can strive for less?",
           "Why reach new heights when you can stay at ground level?",
           "Why be an author when you can be a reader?",
           "The race to the bottom is far less crowded",
           "Why be exceptional when you can be exceptionally average?",
           "Why challenge yourself when you can just not?",
           "The road less traveled is less traveled for a reason",
           "Why explore new horizons when you can look at them from a distance?",
           "Why take the leap when you can take a step back?",
           "Why raise the bar when you can lower it?",
           "Goals are just glorified dreams, and dreams don't come true",
           "The less you expect, the less you have to lose",
           "Why go out on a limb when you can stay in the trunk?",
           "Why be the early bird when you can be the late worm?",
           "Why think outside the box when you can stay safely inside it?",
           "The best way to avoid disappointment is to never try",
           "Why reach for the sky when you can lie on the ground?",
           "The rat race is for rats, not humans",
           "Success is just failure with more steps",
           "The key to failure is to strive for success",
           "Why leave a mark when you can be easily forgotten?",
           "The pursuit of happiness is a chase with no finish line",
           "I don't have low standards; I have realistic expectations",
           "Why be an overachiever when you can be an underwhelmer?",
           "Why be an optimist when you can be a pessimist and be right?",
           "Life is an endless loop of disappointing events",
           "Taking initiative is overrated; taking a nap is underrated",
           "Aspiring for mediocrity is aspiring enough",
           "Why be a pathfinder when you can be a pathfollower?",
           "Why make a difference when you can make no difference at all?",
           "Life is full of hurdles; why not just sit down?",
           "The path of least resistance leads to the least disappointment",
           "Why work smarter when you can work not at all?",
           "Success is just an illusion; failure is the reality",
           "Why change the world when you can change the channel?",
           "The best way to avoid mistakes is to do nothing",
           "Why make plans when you can make excuses?",
           "Dreams are overrated; reality is enough",
           "Success is just another word for more responsibility",
           "Setting the bar low means you'll never trip",
           "Don't follow your heart; follow your couch",
           "In the grand scheme of things, does it really matter?",
           "Why be the star when you can be the background?",
           "Why have a mission when you can have a nap?",
           "The higher you climb, the harder you fall",
           "The more you know, the more you know you don't know",
           "Why make history when you can become a forgotten footnote?",
           "Why be exceptional when you can be forgettable?",
           "The path to success is paved with disappointments",
           "The fewer goals you have, the fewer you can miss",
           "Why be remarkable when you can be unremarkable?",
           "Don't shoot for the moon; you'll miss and be lost in space",
           "Success is just a longer to-do list",
           "Why stretch your limits when you can shrink them?"
       ])->random());

        return 0;
    }

}