<?php

declare(strict_types=1);

namespace JonPurvis\Uninspire\Console\Commands;

use Illuminate\Console\Command;

class UninspireCommand extends Command
{
    /**
     * The signature of the command.
     *
     * @var string
     */
    protected $signature = 'uninspire';

    /**
     * The description of the command.
     *
     * @var string
     */
    protected $description = 'Display an uninspiring quote';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
       $this->comment(collect([
           "Expect the mediocre, and you won't be disappointed.",
           "Why aim for the stars when you can settle for the ceiling?",
           "Dream small, achieve even smaller",
           "Success is overrated; have you tried failure?",
           "Why run when you can walk slowly?",
           "Procrastination: Because there's always tomorrow",
           "Set your goals low, and you'll never be let down",
           "The road to nowhere is paved with indifference",
           "Mistakes: I make them daily",
           "Ambition is for overachievers",
           "Mediocrity is my comfort zone",
           "Average is the new exceptional",
           "Why be a trailblazer when you can follow the herd?",
           "Standing out is too much effort; blending in is just fine",
           "I'm not lazy; I'm conserving energy",
           "The glass is half empty because I drank the other half",
           "Adventure? No thanks, I'll pass",
           "Optimism: It's just a waste of time",
           "Why fly when you can crawl?",
           "Stagnation is my happy place",
           "Life is a series of disappointments, so get used to it",
           "Success is for those who care too much",
           "Why be a go-getter when you can be a go-slower?",
           "Taking risks is so 20th century",
           "Dreams are for people who can't accept reality",
           "Overachievers never truly relax",
           "Effort is overrated; I prefer convenience",
           "Why aim high when you can aim low and still miss?",
           "Good things come to those who wait forever",
           "Expectations are the root of all disappointment",
           "Why be motivated when you can be mediocre?",
           "Settling for less is my life motto",
           "Failing is the first step towards giving up",
           "Why be extraordinary when you can be ordinary?",
           "Procrastination is my superpower",
           "Life is a series of boring moments",
           "Why stand out when you can blend in seamlessly?",
           "Perfectionism is for perfectionists",
           "Taking shortcuts is the way to go",
           "Why hustle when you can snooze?",
           "I'd rather underachieve than overexert",
           "Why try when you can just hope for the best?",
           "Why be ambitious when you can be apathetic?",
           "Success is for those who can't accept failure",
           "Life is a never-ending cycle of monotony",
           "Why climb mountains when you can stay in bed?",
           "Ambition leads to exhaustion",
           "Why reach for the stars when you can gaze at them from afar?",
           "Dreams are for people with too much time on their hands",
           "Why be a winner when you can be a whiner?",
           "Why be a leader when you can be a follower?",
           "Mediocrity is the key to an uneventful life",
           "Why be punctual when you can be perpetually late?",
           "Effort is for those who can't avoid it",
           "Why excel when you can excel at mediocrity?",
           "Setting goals is just a form of self-punishment",
           "I'm not a quitter; I'm a non-starter",
           "Why be a legend when you can be forgettable?",
           "Life is a never-ending sea of monotony",
           "Adventure is overrated; routine is where it's at",
           "Ambition is for the overly optimistic",
           "Why achieve greatness when you can achieve averageness?",
           "Why have high hopes when you can have low expectations?",
           "Why innovate when you can imitate?",
           "Why be enthusiastic when you can be indifferent?",
           "Why be proactive when you can be passive?",
           "Why aim for the moon when you can stay grounded?",
           "Striving for excellence? Nah, I'm good with mediocrity",
           "I'm not a slacker; I'm a strategic energy saver",
           "Ambition is just another word for unnecessary stress",
           "Optimism is for the delusional",
           "Why be a trendsetter when you can be a trend-follower?",
           "Why make waves when you can float along peacefully?",
           "I'm not avoiding work; I'm perfecting my leisure skills",
           "Why be fearless when you can fear everything?",
           "Life's too short to bother with success",
           "Why try when you can fail effortlessly?",
           "Why be a pioneer when you can be a settler?",
           "Overachievement is for overrated people",
           "Life is a series of uninspiring moments",
           "Why strive for greatness when you can settle for adequacy?",
           "Optimism is the path to disappointment",
           "Why be ambitious when you can be complacent?",
           "Why be a hero when you can be a zero?",
           "Taking risks is for those who care too much",
           "Why be a doer when you can be a dreamer?",
           "I'm not lazy; I'm conserving my motivation",
           "Why be diligent when you can be disinterested?",
           "Why aim for the best when you can aim for the rest?",
           "Life is a long journey to mediocrity",
           "Success is for the overly enthusiastic",
           "Why reach for the stars when you can aim for the gutter?",
           "Why work hard when you can hardly work?",
           "Effort is for those with too much time on their hands",
           "Why excel when you can embrace mediocrity?",
           "Why set goals when you can simply drift?",
           "I'm not a quitter; I'm a professional procrastinator",
           "Why be a winner when you can be a non-competitor?",
           "Why be a go-getter when you can be a go-slower?",
           "Ambition is the road to nowhere",
           "Why be creative when you can copy and paste?",
           "Success is for people with too much ambition",
           "Why take action when you can take a nap?",
           "Life is a collection of missed opportunities",
           "Why achieve when you can underachieve?",
           "Why be a legend in your own mind when you can be utterly forgettable?",
           "Why be a winner when you can be a spectator?",
           "Dreaming is for dreamers; I'm a realist",
           "Optimism is for those who haven't faced reality",
           "Why go above and beyond when you can stay beneath the radar?",
           "Ambition is just a fancy word for stress",
           "Why set high expectations when you can set none at all?",
           "Why reach for greatness when you can reach for the TV remote?",
           "I'm not late; I'm fashionably delayed",
           "Why put in effort when you can just put in the minimum required?",
           "Life is an endless series of uninspired moments",
           "Why seek inspiration when you can find a comfortable couch?",
           "Why follow your dreams when you can follow your sleep?",
           "Adventure is overrated; the couch is where it's at",
           "Why be motivated when you can be lackadaisical?",
           "Ambition is a one-way ticket to exhaustion",
           "Why innovate when you can stagnate?",
           "Why be passionate when you can be disinterested?",
           "Why take risks when you can take it easy?",
           "Why aim high when you can aim low and still miss the mark?",
           "I'm not a pessimist; I'm a realist with low expectations",
           "Why chase success when you can amble towards obscurity?",
           "Dreams are for those who can't embrace their mediocrity",
           "Why be a high achiever when you can be a low-key observer?",
           "Why be dynamic when you can be lethargic?",
           "Why work hard when you can hardly work at all?",
           "Ambition is a surefire way to complicate your life",
           "Why be a groundbreaker when you can be a copycat?",
           "Why stand out when you can blend into the wallpaper?",
           "Why be diligent when you can be delightfully indifferent?",
           "Effort is for those who can't master the art of avoidance",
           "Why be successful when you can be blissfully unaccomplished?",
           "Life is a continuous stream of uninspiring days",
           "Why strive for excellence when you can embrace mediocrity with open arms?",
           "Why excel when you can exist?",
           "I'm not a quitter; I'm a professional non-starter",
           "Why be a standout when you can be a sit-down?",
           "Why be a hero when you can be a zero with no pressure?",
           "Taking risks is for those who care too much about consequences",
           "Why be a go-getter when you can be a stay-putter?",
           "Why take initiative when you can take a break?",
           "Life is a long journey to nowhere in particular",
           "Success is for those who can't appreciate the beauty of failure",
           "Why aim for the top when you can hang out comfortably in the middle?",
           "Why be a mover and shaker when you can be a couch potato?",
           "Why be a winner when you can be a non-contender?",
           "Ambition leads to complications",
           "Why dream big when you can dream small and never be disappointed?",
           "Why be a pioneer when you can be a follower with less stress?",
           "Why be a high-flyer when you can be a low-hoverer?",
           "Taking the easy way out is just plain easy",
           "Why be innovative when you can be imitative?",
           "Why be enthusiastic when you can be apathetic?",
           "Why be a trendsetter when you can be a trend-avoider?",
           "I'm not avoiding responsibility; I'm avoiding effort",
           "Why be fearless when you can fear everything and stay in your comfort zone?",
           "Life is too short to worry about success",
           "Why try hard when you can hardly try?",
           "Why be a pioneer when you can be a settler with no pressure?",
           "Overachievement is overrated",
           "Life is just a series of uninspiring routines",
           "Why aim for greatness when you can aim for adequacy?",
           "Why be ambitious when you can be ambivalent?",
           "Optimism is for those who can't see the reality of mediocrity",
           "Why be diligent when you can be disinterested?",
           "Why aim for the best when you can settle for the rest?",
           "Life is a long journey to nowhere in particular",
           "Success is for the overly enthusiastic",
           "Why reach for the stars when you can aim for the gutter?",
           "Why work hard when you can hardly work?",
           "Effort is for those with too much time on their hands",
           "Why excel when you can embrace mediocrity?",
           "Why set goals when you can simply drift?",
           "I'm not a quitter; I'm a professional procrastinator",
           "Why be a winner when you can be a non-competitor?",
           "Why be a go-getter when you can be a go-slower?",
           "Ambition is the road to nowhere",
           "Dreaming is for dreamers; I'm a realist",
           "Optimism is for those who haven't faced reality",
           "Why go above and beyond when you can stay beneath the radar?",
           "Ambition is just a fancy word for stress",
           "Why set high expectations when you can set none at all?",
           "Why reach for greatness when you can reach for the TV remote?",
           "I'm not late; I'm fashionably delayed",
           "Why put in effort when you can just put in the minimum required?",
           "Life is an endless series of uninspired moments",
           "Why seek inspiration when you can find a comfortable couch?",
           "Why follow your dreams when you can follow your sleep?",
           "Adventure is overrated; the couch is where it's at",
           "Why be motivated when you can be lackadaisical?",
           "Ambition is a one-way ticket to exhaustion",
       ])->random());

        return 0;
    }

}